#pragma once

// #define FALL_FREEFALL_ACC_THRESHOLD     0.8f   
// #define FALL_IMPACT_ACC_THRESHOLD       1.5f   
// #define FALL_IMPACT_GYRO_THRESHOLD      100.0f
// #define FALL_STILL_GYRO_THRESHOLD_DPS   20.0f

#define FALL_FREEFALL_ACC_THRESHOLD   0.9f
#define FALL_IMPACT_ACC_THRESHOLD     1.3f
#define FALL_IMPACT_GYRO_THRESHOLD    60.0f
#define FALL_STILL_GYRO_THRESHOLD_DPS 30.0f

#define FALL_STILL_ACC_THRESHOLD_G      1.2f
#define FALL_FREEFALL_ACC_TIMEOUT_MS    1000   
#define FALL_STILLNESS_TIME_MS          500     
#define FALL_FREEFALL_Z_THRESHOLD       0.3f
#define FILTER_ALPHA                    0.2f

